Develop
rubensfelipe/ReceitaBoa pull request #9
Opened 2020-06-02 02:18 UTC by rubensfelipe

adicionei um alertDialog após o usuário selecionar uma foto na tela Editar Receita.

Esse alertDialog é o tempo para salvar a foto no FirebaseStorage, recuparar a url da foto do FirebaseStorage e setar a url da foto na classe Receitas para que ao usuário clicar no botão atualizar, a url da foto e os outros dados de texto da receita possam ser alterados no firebasedatabase.

2020-06-02 02:40 UTC, RodrigoAIM requested changes

2020-06-02 02:40 UTC, RodrigoAIM commented on app/src/main/java/com/example/android/receitaboa/activity/EditarReceitaActivity.java
> +                    abrirDialogCarregamento("Aguarde enquanto a foto é carregada!");
Não se deve pôr uma string diretamente dentro do programa, extrair a string para um arquivo de tradução (string.xml)

https://www.andtuts.com/why-and-how-to-use-string-resources/

2020-06-02 02:40 UTC, RodrigoAIM commented on app/src/main/java/com/example/android/receitaboa/activity/EditarReceitaActivity.java
> +                                        "Erro ao salvar a imagem, tente novamente!",
Não se deve pôr uma string diretamente dentro do programa, extrair a string para um arquivo de tradução (string.xml)

https://www.andtuts.com/why-and-how-to-use-string-resources/

2020-06-02 02:40 UTC, RodrigoAIM commented on app/src/main/java/com/example/android/receitaboa/activity/EditarReceitaActivity.java
> +                                        Toast.LENGTH_SHORT).show();
Isolar isso dentro de uma função separada: mostrarToastFracassoFirebase (ou algum nome assim)

2020-06-02 02:40 UTC, RodrigoAIM commented on app/src/main/java/com/example/android/receitaboa/activity/EditarReceitaActivity.java
> +                                        Toast.LENGTH_SHORT).show();
Isolar isso numa função: mostrarToastSucessoFirebase

2020-06-02 02:40 UTC, RodrigoAIM commented on app/src/main/java/com/example/android/receitaboa/activity/EditarReceitaActivity.java
> +                                        "Foto carregada!",
Não se deve pôr uma string diretamente dentro do programa, extrair a string para um arquivo de tradução (string.xml)

https://www.andtuts.com/why-and-how-to-use-string-resources/

2020-06-02 02:40 UTC, RodrigoAIM commented on app/src/main/java/com/example/android/receitaboa/activity/EditarReceitaActivity.java
>                              }
Isolar isso numa função aparte: recuperarFotoFirebase

2020-06-02 02:40 UTC, RodrigoAIM commented on app/src/main/java/com/example/android/receitaboa/activity/NovaReceitaFotoActivity.java
> +                            "Sua foto foi adicionada com sucesso!",
Não se deve pôr uma string diretamente dentro do programa, extrair a string para um arquivo de tradução (string.xml)

https://www.andtuts.com/why-and-how-to-use-string-resources/

2020-06-03 00:24 UTC, RodrigoDavy approved these changes

2020-06-03 00:35 UTC, merged